version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      # see https://github.com/jenkinsci/jenkins/pull/5112#issuecomment-744429487 and https://github.com/jenkinsci/jenkins/pull/5116#issuecomment-744526638
      # it would be good to update it at some point, but requires significant testing
      - dependency-name: "org.codehaus.groovy:groovy-all"
        versions: [">=2.5.0"]
      # see https://github.com/jenkinsci/jenkins/pull/5184 should be updated with groovy-all
      - dependency-name: "org.fusesource.jansi:jansi"
      # see https://github.com/jenkinsci/jenkins/pull/5144#pullrequestreview-559661934
      # will require source code changes to replace javax.mail with jakarta.mail 
      # and some handling for plugins that depend on javax.mail being provided by Jenkins core.
      - dependency-name: "com.sun.mail:jakarta.mail"
      # this is a banned dependency, we have a hack in our pom to prevent anyone else pulling it in
      - dependency-name: "javax.servlet.servlet-api"
      # needs a jakarta upgrade project, imports changed
      - dependency-name: "jakarta.servlet.jsp.jstl.jakarta.servlet.jsp.jstl-api"
      # Starting with version 2.0.2, this library requires Java 11
      - dependency-name: "org.glassfish.tyrus.bundles:tyrus-standalone-client-jdk"
        versions: [">=2.0.2"]
      # see https://github.com/jenkinsci/jenkins/pull/4224 can't be updated without breaking api
      - dependency-name: "org.jfree:jfreechart"
      # the dependency is actually provided by the Web container, hence it is aligned with Jetty. See https://github.com/jenkinsci/jenkins/pull/5211
      - dependency-name: "javax.servlet:javax.servlet-api"
      # log4j 1.2.17 is the final 1.x release
      - dependency-name: "log4j:log4j"
      # using a newer version clashes in RequireUpperBoundDeps with plugins using a valid script-security dependency
      - dependency-name: "org.jenkins-ci:symbol-annotation"
      # Must remain within jetty 9.x until Java 8 support is removed, ignore jetty 10.x and jetty 11.x updates
      - dependency-name: "org.eclipse.jetty:jetty-maven-plugin"
        versions: [">=10.0.0"]
      # Pending https://github.com/siom79/japicmp/pull/266
      - dependency-name: "com.github.siom79.japicmp:japicmp-maven-plugin"
      # Winstone upgrades require multiple changes in pom.xml.  See https://github.com/jenkinsci/jenkins/pull/5439#discussion_r616418468
      - dependency-name: "org.jenkins-ci:winstone"
      # Starting with version 10.0, this library requires Java 11
      - dependency-name: "com.puppycrawl.tools:checkstyle"
        versions: [">=10.0"]
